In [58]:
# Buatlah sebuah DataFrame dari data jumlah produksi sampah berdasarkan Kabupaten/Kota di Jawa Barat.
#  Pastikan kolom-kolomnya menyertakan nama Kabupaten/Kota, jumlah produksi sampah (dalam ton), dan tahun pencatatan."
import pandas as pd

#Baca data dari file excel 
data_jabar = pd.read_excel('disperkim-od_16985_jumlah_produksi_sampah_berdasarkan_kabupatenkota_v3_data.xlsx', sheet_name='data')
data_jabar

,id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_produksi_sampah,satuan,tahun
0,1,32,JAWA BARAT,3201,KABUPATEN BOGOR,1511.15,TON PER HARI,2015
1,2,32,JAWA BARAT,3202,KABUPATEN SUKABUMI,419.01,TON PER HARI,2015
2,3,32,JAWA BARAT,3203,KABUPATEN CIANJUR,981.41,TON PER HARI,2015
3,4,32,JAWA BARAT,3204,KABUPATEN BANDUNG,1895.94,TON PER HARI,2015
4,5,32,JAWA BARAT,3205,KABUPATEN GARUT,464.74,TON PER HARI,2015
...,...,...,...,...,...,...,...,...
183,184,32,JAWA BARAT,3274,KOTA CIREBON,229.75,TON PER HARI,2021
184,185,32,JAWA BARAT,3275,KOTA BEKASI,1500.77,TON PER HARI,2021
185,186,32,JAWA BARAT,3276,KOTA DEPOK,1418.87,TON PER HARI,2021
186,187,32,JAWA BARAT,3277,KOTA CIMAHI,193.36,TON PER HARI,2021
187,188,32,JAWA BARAT,3278,KOTA TASIKMALAYA,295.87,TON PER HARI,2021

In [64]:
sampah_jabar= pd.DataFrame(data_jabar, columns=['nama_kabupaten_kota','jumlah_produksi_sampah','tahun'])
sampah_jabar

sampah_jabar.to_csv('sampah_jabar.csv')
sampah_jabar.to_excel('sampah_jabar.xlsx')

In [ ]:
# NO 2

d16 = {}  # jumlah sampah pada tahun 2016

for i, row in data_jabar.iterrows():
    tahun = row['tahun']
    sampah = row['jumlah_produksi_sampah']

    if tahun == 2016 and tahun not in d16:
        d16[tahun] = sampah
    elif tahun == 2016:
        d16[tahun] += sampah

print('=============== Data Tahun 2016 ===============')
for i, j in d16.items():
    print(f"Jumlah sampah pada tahun {i} adalah {j:.2f} ton")

df_t2016 = pd.DataFrame([
    {'Tahun': i, 'Total/tahun': j}
    for i, j in d16.items()
])

df_t2016.to_csv('df_t2016.csv', index=False)
df_t2016.to_excel('df_t2016.xlsx', index=False)

=============== Data Tahun 2016 ===============
Jumlah sampah pada tahun 2016 adalah 20969.27 ton

In [52]:
# NO 3
# Jumlahkan Data Pertahun

# Menginisialisasi dictionary untuk menyimpan hasil
thn = {}

# Misalkan df_jabar adalah DataFrame yang telah didefinisikan sebelumnya
for i,j in data_jabar.iterrows():
    tahun = j['tahun']
    total_sampah = j['jumlah_produksi_sampah']

    if tahun not in thn:
        thn[tahun] = total_sampah
    else:
        thn[tahun] += total_sampah

print ('================== Data per Tahun ==================')
for i, j in thn.items():
    print(f'Pada Tahun {i} terdapat : {j:.2f} ton sampah')

df_sampahthn = pd.DataFrame([
    {'Tahun':i, 'Total Sampah' :j}
    for i,j in thn.items()
])

df_sampahthn

df_sampahthn.to_csv('df_sampahthn.csv')
df_sampahthn.to_excel('df_sampahthn.xlsx')

================== Data per Tahun ==================
Pada Tahun 2015 terdapat : 20969.27 ton sampah
Pada Tahun 2016 terdapat : 20969.27 ton sampah
Pada Tahun 2017 terdapat : 20969.27 ton sampah
Pada Tahun 2018 terdapat : 22772.92 ton sampah
Pada Tahun 2019 terdapat : 24490.56 ton sampah
Pada Tahun 2020 terdapat : 25333.00 ton sampah
Pada Tahun 2021 terdapat : 15675.07 ton sampah

In [54]:
# NO 4
# Jumlahkan data per Kota/Kabupaten per tahun
total_kab_kot = {}

for i,j in df_jabar.iterrows():
     daerah = j['nama_kabupaten_kota']
     sampah = j['jumlah_produksi_sampah']
     
     if daerah not in total_kab_kot : 
          total_kab_kot[daerah] = sampah
     else : 
          total_kab_kot[daerah] += sampah
print ('===================== Data Per Daerah =====================')
for i, j in total_kab_kot.items():
     print (f'Pada Daerah{i} terdapat {j:.2f} ton sampah')

df_smphderah = pd.DataFrame([
     {'Nama Kabupaten/Kota' :i, 'Total Sampah' : j}
     for i, j in total_kab_kot.items()
])
df_smphderah
df_sampahthn.to_csv('df_totalkabkot.csv')
df_sampahthn.to_excel('df_totalkabkot.xlsx')

===================== Data Per Daerah =====================
Pada DaerahKABUPATEN BOGOR terdapat 13113.49 ton sampah
Pada DaerahKABUPATEN SUKABUMI terdapat 4038.19 ton sampah
Pada DaerahKABUPATEN CIANJUR terdapat 6497.92 ton sampah
Pada DaerahKABUPATEN BANDUNG terdapat 11934.04 ton sampah
Pada DaerahKABUPATEN GARUT terdapat 4484.29 ton sampah
Pada DaerahKABUPATEN TASIKMALAYA terdapat 3531.33 ton sampah
Pada DaerahKABUPATEN CIAMIS terdapat 2329.72 ton sampah
Pada DaerahKABUPATEN KUNINGAN terdapat 2486.63 ton sampah
Pada DaerahKABUPATEN CIREBON terdapat 3205.17 ton sampah
Pada DaerahKABUPATEN MAJALENGKA terdapat 2593.39 ton sampah
Pada DaerahKABUPATEN SUMEDANG terdapat 2532.71 ton sampah
Pada DaerahKABUPATEN INDRAMAYU terdapat 5383.18 ton sampah
Pada DaerahKABUPATEN SUBANG terdapat 4735.53 ton sampah
Pada DaerahKABUPATEN PURWAKARTA terdapat 2262.90 ton sampah
Pada DaerahKABUPATEN KARAWANG terdapat 5997.44 ton sampah
Pada DaerahKABUPATEN BEKASI terdapat 11328.27 ton sampah
Pada DaerahKABUPATEN BANDUNG BARAT terdapat 4972.37 ton sampah
Pada DaerahKABUPATEN PANGANDARAN terdapat 1277.55 ton sampah
Pada DaerahKOTA BOGOR terdapat 5952.47 ton sampah
Pada DaerahKOTA SUKABUMI terdapat 1833.73 ton sampah
Pada DaerahKOTA BANDUNG terdapat 14521.78 ton sampah
Pada DaerahKOTA CIREBON terdapat 1887.57 ton sampah
Pada DaerahKOTA BEKASI terdapat 15504.31 ton sampah
Pada DaerahKOTA DEPOK terdapat 12209.61 ton sampah
Pada DaerahKOTA CIMAHI terdapat 3112.35 ton sampah
Pada DaerahKOTA TASIKMALAYA terdapat 2754.78 ton sampah
Pada DaerahKOTA BANJAR terdapat 698.64 ton sampah